second: fix compile errors due to unknown types
gcc -m32 -Os -Wall -I. -I../include -fomit-frame-pointer
-fno-strict-aliasing -DSMALL_RELOC=0x280000 -DLARGE_RELOC=0x380000
-fno-stack-protector -DTFTP -c -o mainnet.o main.c
In file included from ../include/ext2fs/ext2fs.h:77,
                 from ./file.h:23,
                 from file.c:23:
../include/ext2fs/ext2_io.h:39: error: expected declaration
specifiers or '...' before 'size_t'

Signed-off-by: Jan Engelhardt <jengelh@medozas.de>